apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dot-25924 
  janus-idp.io/tekton: dot-25924
  backstage.io/kubernetes-id: dot-25924
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dot-25924
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  